# Generated by Django 5.2.8 on 2025-11-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('p_v_App', '0011_company_default_printer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('open', 'Em aberto'), ('paid', 'Pago')], default='open', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('payment_method', models.CharField(blank=True, max_length=20, verbose_name='Forma de pagamento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='clients.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='p_v_App.company')),
            ],
            options={
                'verbose_name': 'Débito',
                'verbose_name_plural': 'Débitos',
                'ordering': ['-created_at'],
            },
        ),
    ]
