# Generated by Django 5.2.8 on 2026-02-08 18:49

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('p_v_App', '0016_company_auto_open_print'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible_public', models.BooleanField(default=False, verbose_name='Visível no Catálogo Público')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog_categories/', verbose_name='Imagem da Categoria')),
                ('description_public', models.TextField(blank=True, verbose_name='Descrição Pública')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_info', to='p_v_App.category', verbose_name='Categoria Base')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='p_v_App.company')),
            ],
            options={
                'verbose_name': 'Categoria do Catálogo',
                'verbose_name_plural': 'Categorias do Catálogo',
                'ordering': ['display_order', 'category__name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Número do Pedido')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Telefone do Cliente')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Observações do Cliente')),
                ('items', models.JSONField(help_text='Lista de produtos com quantidades', verbose_name='Itens do Pedido')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_preparo', 'Em Preparo'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='novo', max_length=20, verbose_name='Status')),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado via WhatsApp em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='p_v_App.company')),
            ],
            options={
                'verbose_name': 'Pedido do Catálogo',
                'verbose_name_plural': 'Pedidos do Catálogo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible_public', models.BooleanField(default=False, verbose_name='Visível no Catálogo Público')),
                ('highlighted', models.BooleanField(default=False, verbose_name='Produto em Destaque')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('public_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Descrição Pública')),
                ('view_count', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='p_v_App.company')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_info', to='p_v_App.products', verbose_name='Produto Base')),
            ],
            options={
                'verbose_name': 'Produto do Catálogo',
                'verbose_name_plural': 'Produtos do Catálogo',
                'ordering': ['display_order', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_enabled', models.BooleanField(default=False, verbose_name='Catálogo Habilitado')),
                ('catalog_slug', models.SlugField(help_text='URL única para acesso público (ex: pizzaria-do-joao)', max_length=100, unique=True, verbose_name='URL do Catálogo')),
                ('catalog_title', models.CharField(max_length=200, verbose_name='Título do Catálogo')),
                ('catalog_description', models.TextField(blank=True, verbose_name='Descrição')),
                ('whatsapp_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Número de telefone inválido. Use formato internacional.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Número WhatsApp')),
                ('custom_message_template', models.TextField(default='Olá! Sou {customer_name} e gostaria de fazer um pedido.\n\n📋 Pedido #{order_number}\n\n🛒 Itens:\n{items}\n\n💰 Total: {total}\n\n📝 Observações:\n{notes}\n\nAguardo confirmação!', help_text='Variáveis: {customer_name}, {order_number}, {items}, {total}, {notes}', verbose_name='Template da Mensagem')),
                ('display_prices', models.BooleanField(default=True, verbose_name='Exibir Preços')),
                ('primary_color', models.CharField(default='#002d6c', max_length=7, validators=[django.core.validators.RegexValidator(message='Código de cor hexadecimal inválido', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor Primária')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='catalog_logos/', verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_settings', to='p_v_App.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração do Catálogo',
                'verbose_name_plural': 'Configurações do Catálogo',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog_products/', verbose_name='Imagem')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Imagem Principal')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto Alternativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='p_v_App.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='p_v_App.products', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens dos Produtos',
                'ordering': ['-is_primary', 'display_order'],
            },
        ),
    ]
