# Generated by Django 5.2.8 on 2026-02-08 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_v_App', '0016_company_auto_open_print'),
        ('public_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60, verbose_name='Ação')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('object_type', models.CharField(blank=True, max_length=120, verbose_name='Tipo do Objeto')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='ID do Objeto')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='p_v_App.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Auditoria do Catálogo',
                'verbose_name_plural': 'Auditorias do Catálogo',
                'ordering': ['-created_at'],
            },
        ),
    ]
