# Generated by Django 5.2.8 on 2026-02-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_catalog', '0002_catalogauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogorder',
            name='delivery_address',
            field=models.TextField(blank=True, default='', verbose_name='Endereço de Entrega'),
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='payment_method',
            field=models.CharField(choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('MULTI', 'Pagamentos múltiplos')], default='PIX', max_length=10, verbose_name='Forma de Pagamento'),
        ),
    ]
