# Generated by Django 5.1.7 on 2025-07-30 06:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True,
                 max_length=100, null=True, verbose_name='Nome do Cliente')),
                ('code', models.CharField(max_length=100)),
                ('sub_total', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('grand_total', models.FloatField(default=0)),
                ('tendered_amount', models.FloatField(default=0)),
                ('amount_change', models.FloatField(default=0)),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('DEBITO', 'Débito'), (
                    'CREDITO', 'Crédito')], default='PIX', max_length=10, verbose_name='Forma de Pagamento')),
                ('endereco_entrega', models.CharField(blank=True,
                 max_length=255, null=True, verbose_name='Endereço (Entrega)')),
                ('taxa_entrega', models.FloatField(
                    default=0, verbose_name='Taxa de Entrega')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_rota', 'Em rota'), (
                    'entregue', 'Entregue')], default='pendente', help_text='Só relevante para pedidos', max_length=10)),
                ('date_added', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True,
                 max_length=100, null=True, verbose_name='Nome do Cliente')),
                ('code', models.CharField(max_length=100)),
                ('sub_total', models.FloatField(default=0)),
                ('grand_total', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('tendered_amount', models.FloatField(default=0)),
                ('amount_change', models.FloatField(default=0)),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('DEBITO', 'Débito'), (
                    'CREDITO', 'Crédito')], default='PIX', max_length=10, verbose_name='Forma de Pagamento')),
                ('endereco_entrega', models.CharField(blank=True, help_text='Informe o endereço, se necessário, para ser exibido na nota.',
                 max_length=255, null=True, verbose_name='Endereço (Entrega)')),
                ('type', models.CharField(choices=[('venda', 'Venda'), ('pedido', 'Pedido')], default='venda',
                 help_text='Define se é venda imediata ou pedido para delivery', max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_rota', 'Em rota'), (
                    'entregue', 'Entregue')], default='pendente', help_text='Só relevante se type="pedido"', max_length=10)),
                ('date_added', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('custo', models.FloatField(default=0.0)),
                ('date_added', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='p_v_App.category')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('qty', models.FloatField(default=0)),
                ('taxa_entrega', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('pedido', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='p_v_App.pedido')),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='p_v_App.products')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=0)),
                ('validade', models.IntegerField(choices=[(0, 'Sem Validade'), (30, 'Validade de 30 dias'), (60, 'Validade de 60 dias'), (
                    90, 'Validade de 90 dias'), (120, 'Validade de 120 dias'), (180, 'Validade de 180 dias'), (365, 'Validade de 365 dias')], default=0)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('preco', models.FloatField(default=0)),
                ('custo', models.FloatField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('categoria', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='p_v_App.category')),
                ('descricao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='estoque_descricao', to='p_v_App.products')),
                ('produto', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='p_v_App.products')),
            ],
        ),
        migrations.CreateModel(
            name='salesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('qty', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('product_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='p_v_App.products')),
                ('sale_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='p_v_App.sales')),
            ],
        ),
    ]
