# Generated by Django 5.2.5 on 2025-08-14 16:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_v_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    max_length=200, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18,
                 null=True, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True,
                 max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True,
                 max_length=20, null=True, verbose_name='Telefone')),
                ('address', models.TextField(blank=True,
                 null=True, verbose_name='Endereço')),
                ('is_active', models.BooleanField(
                    default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='Atualizado em')),
                ('tax_rate', models.FloatField(
                    default=0.0, verbose_name='Taxa de Imposto (%)')),
                ('delivery_fee', models.FloatField(
                    default=0.0, verbose_name='Taxa de Entrega Padrão')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='%(class)s_set', to='p_v_App.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estoque',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='%(class)s_set', to='p_v_App.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='%(class)s_set', to='p_v_App.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='%(class)s_set', to='p_v_App.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='%(class)s_set', to='p_v_App.company'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('is_company_admin', models.BooleanField(
                    default=False, verbose_name='Administrador da Empresa')),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='users', to='p_v_App.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
