# Generated by Django 5.1.7 on 2025-10-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_v_App', '0004_sales_table_sales_table_order_alter_sales_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='delivery_fee',
            field=models.FloatField(default=0, verbose_name='Taxa de Entrega'),
        ),
    ]
