# Generated by Django 5.1.7 on 2025-10-27 15:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_v_App', '0005_sales_delivery_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(
                choices=[
                    ('PIX', 'Pix'),
                    ('DINHEIRO', 'Dinheiro'),
                    ('DEBITO', 'Débito'),
                    ('CREDITO', 'Crédito'),
                    ('MULTI', 'Pagamentos múltiplos'),
                ],
                default='PIX',
                max_length=10,
                verbose_name='Forma de Pagamento',
            ),
        ),
        migrations.AlterField(
            model_name='sales',
            name='forma_pagamento',
            field=models.CharField(
                choices=[
                    ('PIX', 'Pix'),
                    ('DINHEIRO', 'Dinheiro'),
                    ('DEBITO', 'Débito'),
                    ('CREDITO', 'Crédito'),
                    ('MULTI', 'Pagamentos múltiplos'),
                ],
                default='PIX',
                max_length=10,
                verbose_name='Forma de Pagamento',
            ),
        ),
        migrations.AlterField(
            model_name='tableorder',
            name='payment_method',
            field=models.CharField(
                blank=True,
                choices=[
                    ('PIX', 'Pix'),
                    ('DINHEIRO', 'Dinheiro'),
                    ('DEBITO', 'Débito'),
                    ('CREDITO', 'Crédito'),
                    ('MULTI', 'Pagamentos múltiplos'),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name='CashRegisterSession',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'opening_amount',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal('0.00'))
                        ],
                    ),
                ),
                (
                    'closing_amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal('0.00'))
                        ],
                    ),
                ),
                ('opening_note', models.TextField(blank=True)),
                ('closing_note', models.TextField(blank=True)),
                (
                    'status',
                    models.CharField(
                        choices=[('open', 'Aberto'), ('closed', 'Fechado')],
                        default='open',
                        max_length=10,
                    ),
                ),
                ('opened_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'closed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='cash_sessions_closed',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_set',
                        to='p_v_App.company',
                    ),
                ),
                (
                    'opened_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='cash_sessions_opened',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Sessão de caixa',
                'verbose_name_plural': 'Sessões de caixa',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('entry', 'Entrada'), ('exit', 'Saída')], max_length=5
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal('0.00'))
                        ],
                    ),
                ),
                (
                    'payment_method',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('PIX', 'Pix'),
                            ('DINHEIRO', 'Dinheiro'),
                            ('DEBITO', 'Débito'),
                            ('CREDITO', 'Crédito'),
                            ('MULTI', 'Pagamentos múltiplos'),
                            ('AJUSTE', 'Ajuste manual'),
                        ],
                        max_length=10,
                    ),
                ),
                ('description', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                (
                    'recorded_at',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_set',
                        to='p_v_App.company',
                    ),
                ),
                (
                    'recorded_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='cash_movements',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'sale',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='cash_movements',
                        to='p_v_App.sales',
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='movements',
                        to='p_v_App.cashregistersession',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Movimentação de caixa',
                'verbose_name_plural': 'Movimentações de caixa',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'method',
                    models.CharField(
                        choices=[
                            ('PIX', 'Pix'),
                            ('DINHEIRO', 'Dinheiro'),
                            ('DEBITO', 'Débito'),
                            ('CREDITO', 'Crédito'),
                            ('MULTI', 'Pagamentos múltiplos'),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    'tendered_amount',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal('0.00'))
                        ],
                    ),
                ),
                (
                    'applied_amount',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal('0.00'))
                        ],
                    ),
                ),
                (
                    'change_amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal('0.00'))
                        ],
                    ),
                ),
                (
                    'recorded_at',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_set',
                        to='p_v_App.company',
                    ),
                ),
                (
                    'recorded_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='sale_payments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'sale',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payments',
                        to='p_v_App.sales',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Pagamento de venda',
                'verbose_name_plural': 'Pagamentos de vendas',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
