# Generated by Django 5.1.7 on 2025-10-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_v_App', '0006_alter_pedido_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='discount_reason',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Motivo do desconto'
            ),
        ),
        migrations.AddField(
            model_name='pedido',
            name='discount_total',
            field=models.FloatField(
                default=0, verbose_name='Desconto aplicado'),
        ),
        migrations.AddField(
            model_name='sales',
            name='discount_reason',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Motivo do desconto'
            ),
        ),
        migrations.AddField(
            model_name='sales',
            name='discount_total',
            field=models.FloatField(
                default=0, verbose_name='Desconto aplicado'),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
