# Generated by Django 5.1.7 on 2025-10-30 17:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_v_App', '0007_pedido_discount_reason_pedido_discount_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='combo_max_flavors',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='Número máximo de itens diferentes permitidos por combo.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='products',
            name='combo_total_quantity',
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text='Quantidade total consumida por venda do combo.',
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='products',
            name='is_combo',
            field=models.BooleanField(default=False),
        ),

        # ▼▼▼ SUBSTITUIR o AlterField ORIGINAL por este bloco ▼▼▼
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # não tocar no banco; já é movement_type
            state_operations=[
                migrations.AlterField(
                    model_name='cashmovement',
                    name='type',
                    field=models.CharField(
                        choices=[('entry', 'Entrada'), ('exit', 'Saída')],
                        db_column='movement_type',
                        max_length=5,
                    ),
                ),
            ],
        ),
        # ▲▲▲ FIM DA SUBSTITUIÇÃO ▲▲▲

        migrations.CreateModel(
            name='PedidoComboItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    'component',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='p_v_App.products',
                    ),
                ),
                (
                    'pedido_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='combo_components',
                        to='p_v_App.pedidoitem',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Componente de Combo (Pedido)',
                'verbose_name_plural': 'Componentes de Combo (Pedidos)',
            },
        ),
        migrations.CreateModel(
            name='SaleComboItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    'component',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='p_v_App.products',
                    ),
                ),
                (
                    'sale_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='combo_components',
                        to='p_v_App.salesitems',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Componente de Combo (Venda)',
                'verbose_name_plural': 'Componentes de Combo (Vendas)',
            },
        ),
        migrations.CreateModel(
            name='ProductComboItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'quantity',
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal('0.000'),
                        help_text='Quantidade padrão consumida por combo.',
                        max_digits=12,
                    ),
                ),
                (
                    'combo',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='combo_items',
                        to='p_v_App.products',
                    ),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_set',
                        to='p_v_App.company',
                    ),
                ),
                (
                    'component',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='component_of_combos',
                        to='p_v_App.products',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Item de Combo',
                'verbose_name_plural': 'Itens de Combo',
                'unique_together': {('combo', 'component', 'company')},
            },
        ),
    ]
