# Generated by Django 5.1.7 on 2025-10-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_v_App', '0008_products_combo_max_flavors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashmovement',
            old_name='type',
            new_name='movement_type',
        ),
    ]
