# Generated by Django 5.1.7 on 2025-10-30 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_v_App', '0009_rename_type_cashmovement_movement_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashmovement',
            old_name='movement_type',
            new_name='type',
        ),
    ]
