# Generated by Django 5.1.7 on 2025-11-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_v_App', '0010_rename_movement_type_cashmovement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_printer',
            field=models.CharField(blank=True, help_text='Nome ou caminho da impressora padrão deste tenant.', max_length=120, verbose_name='Impressora padrão'),
        ),
    ]
