# Generated by Django 5.2.8 on 2025-11-23 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('p_v_App', '0011_company_default_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clients.client'),
        ),
        migrations.AddField(
            model_name='sales',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='clients.client'),
        ),
    ]
