# Generated by Django 5.2.8 on 2025-11-25 22:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p_v_App', '0012_pedido_client_sales_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('MULTI', 'Pagamentos múltiplos')], max_length=10)),
                ('tendered_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('change_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidopayment_set', to='p_v_App.company')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='p_v_App.pedido')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento de pedido',
                'verbose_name_plural': 'Pagamentos de pedidos',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
