# Generated by Django 5.1.7 on 2025-11-25 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_v_App', '0013_pedidopayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidopayment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='p_v_App.company'),
        ),
    ]
