# Generated by Django 5.2.8 on 2025-11-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_v_App', '0015_sales_venda_a_prazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_open_print',
            field=models.BooleanField(default=True, help_text='Quando marcado, a tela de impressão abre automaticamente após concluir uma venda ou pedido.', verbose_name='Abrir tela de impressão após finalizar'),
        ),
    ]
